version: '3'

services:
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:11.5
    network_mode: host
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjsx_crud
